export const AlertTypes = {
    ABNORMAL_HEART_RATE: 'ABNORMAL_HEART_RATE',
    ABNORMAL_BLOOD_PRESSURE: 'ABNORMAL_BLOOD_PRESSURE',
    ABNORMAL_TEMPERATURE: 'ABNORMAL_TEMPERATURE',
    LOW_OXYGEN_SATURATION: 'LOW_OXYGEN_SATURATION'
} as const;